import { bodyStateAtIndex, type PredictionCheck, type Recording, type RunMetrics, type Scenario } from "@physicslab/shared";
import type { Interpretation } from "@physicslab/shared";
import { fmt, fmtUnit } from "./format";

export function download(filename: string, content: string, type = "text/plain") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "scenario";

const csvCell = (v: string | number) => {
  const s = typeof v === "number" ? (Number.isFinite(v) ? String(Number(v.toPrecision(10))) : "") : v;
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

/** One row per recorded sample: time, per-object kinematics and energies, system energy. */
export function recordingToCsv(rec: Recording, labels: Record<string, string> = {}): string {
  const dyn = rec.bodyOrder.filter((id) => rec.bodies[id].dynamic);
  const header = ["time_s"];
  for (const id of dyn) {
    const n = labels[id] ?? id;
    header.push(...["x_m", "y_m", "z_m", "vx_m_s", "vy_m_s", "vz_m_s", "speed_m_s", "kinetic_J", "potential_J"].map((c) => `${n}.${c}`));
  }
  header.push("system.kinetic_J", "system.gravitational_J", "system.elastic_J", "system.total_J");
  const rows = [header.map(csvCell).join(",")];
  for (let i = 0; i < rec.sampleCount; i++) {
    const row: number[] = [rec.times[i]];
    for (const id of dyn) {
      const s = bodyStateAtIndex(rec.bodies[id], i);
      row.push(...s.position, ...s.velocity, Math.hypot(...s.velocity), s.kinetic, s.potential);
    }
    row.push(rec.energy.kinetic[i], rec.energy.gravitational[i], rec.energy.elastic[i], rec.energy.total[i]);
    rows.push(row.map(csvCell).join(","));
  }
  return rows.join("\n");
}

export function markdownReport(opts: {
  scenario: Scenario;
  interpretation?: Interpretation | null;
  checks: PredictionCheck[];
  metrics: RunMetrics | null;
  labels: Record<string, string>;
}): string {
  const { scenario: s, interpretation: it, checks, metrics, labels } = opts;
  const lines: string[] = [`# ${s.metadata.name}`, "", `_Generated by PhysicsLab on ${new Date().toLocaleString()}_`, ""];
  if (s.metadata.description) lines.push(`> ${s.metadata.description}`, "");
  if (it) {
    lines.push("## Interpretation", "", it.summary, "");
    if (it.objects.length) lines.push("### Objects", "", ...it.objects.map((o) => `- **${o.name}** — ${o.details}`), "");
    if (it.forces.length) lines.push("### Forces", "", ...it.forces.map((f) => `- **${f.name}** — ${f.details}`), "");
    if (it.assumptions.length) lines.push("### Assumptions", "", ...it.assumptions.map((a) => `- ${a}`), "");
  }
  if (checks.length) {
    lines.push("## Predictions vs simulation", "", "| Quantity | Predicted | Simulated | Difference |", "|---|---|---|---|");
    for (const c of checks) {
      const p = c.prediction;
      const diff = c.error === null ? "—" : p.unit === "%" ? `${fmt(c.error)} pts` : `${fmt(c.error * 100)}%`;
      lines.push(`| ${p.label} | ${fmtUnit(p.value, p.unit)} | ${c.measured === null ? "—" : fmtUnit(c.measured, p.unit)} | ${diff} |`);
    }
    lines.push("", "Formulas:", "", ...checks.map((c) => `- ${c.prediction.formula}`), "");
  }
  if (metrics) {
    lines.push("## Results", "", "| Object | Max speed | Final speed | Distance travelled | Max height | Comes to rest |", "|---|---|---|---|---|---|");
    for (const o of metrics.objects) {
      lines.push(`| ${labels[o.id] ?? o.id} | ${fmtUnit(o.maxSpeed, "m/s")} | ${fmtUnit(o.finalSpeed, "m/s")} | ${fmtUnit(o.pathLength, "m")} | ${fmtUnit(o.maxHeight, "m")} | ${o.timeToRest === null ? "no" : fmtUnit(o.timeToRest, "s")} |`);
    }
    lines.push("", `Energy: ${fmt(metrics.energyStart)} J at the start, ${fmt(metrics.energyEnd)} J at the end (${fmt(metrics.energyLostPercent)}% of peak kinetic energy lost). ${metrics.collisions} contact events.`, "");
  }
  lines.push("## Scenario JSON", "", "```json", JSON.stringify(s, null, 2), "```", "");
  return lines.join("\n");
}
